#!/bin/bash
#!/usr/local/bin/gnuplot -persist

array=( 0.045  0.09 0.27 0.54 0.90  2.70 )
for j in "${array[@]}"
do

cd ${j}salt
rm rdf_weo*

gmx rdf  -f  NPT_rdf.xtc  -s  NPT_rdf.tpr  -pbc      -selrpos  mol_com -seltype  mol_com  -b 100 -ref 4 -sel 0 -o rdf_weo.xvg

cd ..
done
